#!/bin/bash

LIB_NAME="ParMetis"
LIB_VERSION="3.2.0"

source ${HOME}/script/select-compiler

BUILD_DIR=${HOME}/lib/${COMPILER}/${LIB_NAME}-build
SOURCE_DIR=${HOME}/lib/${LIB_NAME}-${LIB_VERSION}
INSTALL_DIR=${HOME}/lib/${COMPILER}/${LIB_NAME}-${LIB_VERSION}
C_FLAG=${C_FLAGS_OPT}

mkdir -p ${INSTALL_DIR}/include/metis
mkdir -p ${INSTALL_DIR}/lib

cd ${SOURCE_DIR}

cat > Makefile.in <<EOF
CC=${MPI_ROOT}/bin/mpicc
OPTFLAGS=${C_FLAG}
LD=${MPI_ROOT}/bin/mpicc
AR=${MYAR} rv
RANLIB=${MYAR} -ts
EOF

make clean || return 1
make || return 1

# Installing
install -m 664 -g lifev lib{metis,parmetis}.a ${INSTALL_DIR}/lib
install -m 664 -g lifev parmetis.h ${INSTALL_DIR}/include
install -m 664 -g lifev METISLib/*.h ${INSTALL_DIR}/include/metis

unset INSTALL_DIR
