#!/bin/bash

LIB_NAME="trilinos"
LIB_VERSION="10.12.2"

source ${HOME}/script/select-compiler

BUILD_DIR=${HOME}/lib/${COMPILER}/${LIB_NAME}-build
SOURCE_DIR=${HOME}/lib/${LIB_NAME}-${LIB_VERSION}-Source
INSTALL_DIR=${HOME}/lib/${COMPILER}/${LIB_NAME}-$LIB_VERSION

CXX_FLAGS="${CXX_FLAGS_OPT}"
C_FLAGS=${CXX_FLAGS_OPT}
Fortran_FLAGS=${Fortran_FLAGS_OPT}
LIBS_DIR="${HOME}/lib/${COMPILER}"
SUITESPARSE="${LIBS_DIR}/suitesparse-install"

mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}
rm -f CMakeCache.txt

cmake \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_C_COMPILER:STRING="${MPI_ROOT}/bin/mpicc" \
  -D CMAKE_CXX_COMPILER:STRING="${MPI_ROOT}/bin/mpicxx" \
  -D CMAKE_CXX_FLAGS:STRING="${CXX_FLAGS}" \
  -D CMAKE_C_FLAGS:STRING="${C_FLAGS}" \
  -D CMAKE_Fortran_COMPILER:STRING="${MPI_ROOT}/bin/mpif90" \
  -D CMAKE_Fortran_FLAGS:STRING="${Fortran_FLAGS}" \
  -D CMAKE_AR:STRING="${MYAR}" \
  -D CMAKE_INSTALL_PREFIX:STRING="${INSTALL_DIR}" \
  -D BUILD_SHARED_LIBS:BOOL=OFF \
  \
  -D Trilinos_ENABLE_NOX:BOOL=ON \
  -D Trilinos_ENABLE_Thyra:BOOL=OFF \
  -D Trilinos_ENABLE_Rythmos:BOOL=ON \
  -D Trilinos_ENABLE_ML:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack:BOOL=ON \
  -D Trilinos_ENABLE_Amesos:BOOL=ON \
  -D Trilinos_ENABLE_Anasazi:BOOL=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  \
  -D Epetra_ENABLE_TESTS:BOOL=ON \
  \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_BASE_DIR:PATH="${MPI_ROOT}" \
  \
  -D TPL_ENABLE_BLAS:BOOL=ON \
  -D BLAS_LIBRARY_DIRS:PATH="/data/libs/blas/${COMPILER}/${FPIC_BLAS}" \
  -D TPL_ENABLE_LAPACK:BOOL=ON \
  -D LAPACK_LIBRARY_DIRS:PATH="/data/libs/lapack/3.3.1/${COMPILER}/${FPIC_LAPACK}" \
  \
  -D TPL_ENABLE_HDF5:BOOL=ON \
  -D HDF5_INCLUDE_DIRS:PATH="${LIBS_DIR}/hdf5-install/include" \
  -D HDF5_LIBRARY_DIRS:PATH="${LIBS_DIR}/hdf5-install/lib" \
  \
  -D TPL_ENABLE_ParMETIS:BOOL=ON \
  -D ParMETIS_INCLUDE_DIRS:PATH="${LIBS_DIR}/ParMetis-install/include" \
  -D ParMETIS_LIBRARY_DIRS:PATH="${LIBS_DIR}/ParMetis-install/lib" \
  \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D TPL_ENABLE_Zlib:BOOL=ON \
  -D TPL_ENABLE_Pthread:BOOL=ON \
  \
  -D TPL_ENABLE_UMFPACK:BOOL=ON \
  -D UMFPACK_INCLUDE_DIRS:PATH="${SUITESPARSE}/include" \
  -D UMFPACK_LIBRARY_DIRS:PATH="${SUITESPARSE}/lib" \
  \
  -D TPL_ENABLE_AMD:BOOL=ON \
  -D AMD_INCLUDE_DIRS:PATH="${SUITESPARSE}/include" \
  -D AMD_LIBRARY_DIRS:PATH="${SUITESPARSE}/lib" \
  \
  -D TPL_ENABLE_SuperLUDist:BOOL=ON \
  -D SuperLUDist_INCLUDE_DIRS:PATH="${LIBS_DIR}/superludist-3.1/include/superludist" \
  -D SuperLUDist_LIBRARY_DIRS:PATH="${LIBS_DIR}/superludist-3.1/lib" \
  \
  $* ${SOURCE_DIR}

# LINKER_FLAGS="-lgfortran -lpthread ${SUITESPARSE}/lib/libcholmod.a ${SUITESPARSE}/lib/libcolamd.a ${SUITESPARSE}/lib/libcamd.a ${SUITESPARSE}/lib/libccolamd.a"
#  -D Trilinos_EXTRA_LINK_FLAGS:STRING="${LINKER_FLAGS}" \
#  -D BLAS_LIBRARY_DIRS:PATH="${MKLROOT}/lib/em64t" \
#  -D BLAS_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
#  -D LAPACK_LIBRARY_DIRS:PATH="${MKLROOT}/lib/em64t" \
#  -D LAPACK_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
#  -D CMAKE_EXE_LINKER_FLAGS:STRING="${LINK_OPTION}" \
