#!/bin/bash


# lifev pat
BUILD_DIR=${HOME}/antonio/build-tmp
SOURCE_DIR=${HOME}/antonio/lifev
INSTALL_DIR=${HOME}/antonio/install-tmp

# libraries
LIFEV_BOOST="/data/libs_exa/boost/1.48.0/gnu"
LIFEV_TRILINOS="/home/lisa/lisa039/lib/gnu/tri1linos-10.10.2"
LIFEV_SUITESPARSE="/home/lisa/lisa039/lib/gnu/suitesparse-install"

# flags
LINKER_FLAGS="-lgfortran -lpthread ${LIFEV_SUITESPARSE}/lib/libcholmod.a ${LIFEV_SUITESPARSE}/lib/libcolamd.a ${LIFEV_SUITESPARSE}/lib/libcamd.a ${LIFEV_SUITESPARSE}/lib/libccolamd.a"

#  -D CMAKE_CXX_FLAGS:STRING="-static -fpermissive"\

cd $BUILD_DIR
rm -f CMakeCache.txt
/home/lisa/lisa039/lib/cmake-install/bin/cmake \
  -D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_DIR}" \
  -D CMAKE_C_COMPILER:STRING="${MPI_ROOT}/bin/mpicc" \
  -D CMAKE_CXX_COMPILER:STRING="${MPI_ROOT}/bin/mpicxx" \
  -D CMAKE_Fortran_COMPILER:STRING="${MPI_ROOT}/bin/mpif90" \
  -D CMAKE_BUILD_TYPE:STRING="RELEASE" \
  -D LifeV_EXTRA_LINK_FLAGS:STRING="${LINKER_FLAGS}" \
  \
  -D LifeV_ENABLE_Core:BOOL=ON \
  \
  -D Trilinos_INCLUDE_DIRS:PATH="${LIFEV_TRILINOS}/include" \
  -D Trilinos_LIBRARY_DIRS:PATH="${LIFEV_TRILINOS}/lib" \
  \
  -D ParMETIS_INCLUDE_DIRS:PATH="/home/lisa/lisa039/lib/gnu/ParMetis-install/include" \
  -D ParMETIS_LIBRARY_DIRS:PATH="/home/lisa/lisa039/lib/gnu/ParMetis-install/lib" \
  \
  -D BLAS_LIBRARY_DIRS:PATH="/data/libs/blas/${COMPILER}/${FPIC_BLAS}" \
  -D LAPACK_LIBRARY_DIRS:PATH="/data/libs/lapack/3.3.1/${COMPILER}/${FPIC_LAPACK}" \
  \
  -D Boost_INCLUDE_DIRS:PATH="/data/libs_exa/boost/1.48.0/gnu/include" \
  \
  $* ${SOURCE_DIR} #--trace 1>&2 2>cmake.log

#  -D LIFE_EXTRA_LINK_LINE:STRING="${LINKER_FLAGS}" \

